// Public bundled fictional illustrations; selecting one never calls a provider.
export const PORTRAIT_PRESETS = Object.freeze(
  [
    {
      id: "portrait-01",
      zh: "雨窗",
      en: "Rainlight",
      url: "/companion/presets/portrait-01.jpg",
      thumbnail: "/companion/presets/portrait-01-thumb.jpg",
    },
    {
      id: "portrait-02",
      zh: "晴页",
      en: "Sunlit Pages",
      url: "/companion/presets/portrait-02.jpg",
      thumbnail: "/companion/presets/portrait-02-thumb.jpg",
    },
    {
      id: "portrait-03",
      zh: "海风",
      en: "Sea Breeze",
      url: "/companion/presets/portrait-03.jpg",
      thumbnail: "/companion/presets/portrait-03-thumb.jpg",
    },
    {
      id: "portrait-04",
      zh: "夜航",
      en: "Nightfall",
      url: "/companion/presets/portrait-04.jpg",
      thumbnail: "/companion/presets/portrait-04-thumb.jpg",
    },
    {
      id: "portrait-05",
      zh: "花序",
      en: "Wildflower",
      url: "/companion/presets/portrait-05.jpg",
      thumbnail: "/companion/presets/portrait-05-thumb.jpg",
    },
    {
      id: "portrait-06",
      zh: "雪松",
      en: "Cedar",
      url: "/companion/presets/portrait-06.jpg",
      thumbnail: "/companion/presets/portrait-06-thumb.jpg",
    },
    {
      id: "portrait-07",
      zh: "晨光",
      en: "Morning Glow",
      url: "/companion/presets/portrait-07.jpg",
      thumbnail: "/companion/presets/portrait-07-thumb.jpg",
    },
    {
      id: "portrait-08",
      zh: "弦音",
      en: "Strings",
      url: "/companion/presets/portrait-08.jpg",
      thumbnail: "/companion/presets/portrait-08-thumb.jpg",
    },
    {
      id: "portrait-09",
      zh: "落日",
      en: "Afterglow",
      url: "/companion/presets/portrait-09.jpg",
      thumbnail: "/companion/presets/portrait-09-thumb.jpg",
    },
    {
      id: "portrait-10",
      zh: "月白",
      en: "Moonlit",
      url: "/companion/presets/portrait-10.jpg",
      thumbnail: "/companion/presets/portrait-10-thumb.jpg",
    },
    {
      id: "portrait-16",
      zh: "微醺",
      en: "Amber Hour",
      url: "/companion/presets/portrait-16.jpg",
      thumbnail: "/companion/presets/portrait-16-thumb.jpg",
    },
    {
      id: "portrait-17",
      zh: "白昼",
      en: "Daylight",
      url: "/companion/presets/portrait-17.jpg",
      thumbnail: "/companion/presets/portrait-17-thumb.jpg",
    },
    {
      id: "portrait-18",
      zh: "墨韵",
      en: "Ink & Ivory",
      url: "/companion/presets/portrait-18.jpg",
      thumbnail: "/companion/presets/portrait-18-thumb.jpg",
    },
    {
      id: "portrait-19",
      zh: "夏柚",
      en: "Citrus Summer",
      url: "/companion/presets/portrait-19.jpg",
      thumbnail: "/companion/presets/portrait-19-thumb.jpg",
    },
    {
      id: "portrait-20",
      zh: "远山",
      en: "Distant Hills",
      url: "/companion/presets/portrait-20.jpg",
      thumbnail: "/companion/presets/portrait-20-thumb.jpg",
    },
    {
      id: "portrait-11",
      zh: "归途",
      en: "Homeward",
      url: "/companion/presets/portrait-11.jpg",
      thumbnail: "/companion/presets/portrait-11-thumb.jpg",
    },
    {
      id: "portrait-12",
      zh: "书间",
      en: "Between Pages",
      url: "/companion/presets/portrait-12.jpg",
      thumbnail: "/companion/presets/portrait-12-thumb.jpg",
    },
    {
      id: "portrait-13",
      zh: "潮汐",
      en: "Tides",
      url: "/companion/presets/portrait-13.jpg",
      thumbnail: "/companion/presets/portrait-13-thumb.jpg",
    },
    {
      id: "portrait-14",
      zh: "星轨",
      en: "Starlines",
      url: "/companion/presets/portrait-14.jpg",
      thumbnail: "/companion/presets/portrait-14-thumb.jpg",
    },
    {
      id: "portrait-15",
      zh: "青野",
      en: "Open Fields",
      url: "/companion/presets/portrait-15.jpg",
      thumbnail: "/companion/presets/portrait-15-thumb.jpg",
    },
  ].map(Object.freeze),
);
export function getPortraitPreset(id) {
  return PORTRAIT_PRESETS.find((p) => p.id === id) ?? null;
}
